# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNxafF9kILY9F690UDzPs0Fa4U5JJTBe
"""

# ==========================================
# 1. CLASE ESTUDIANTE
# ==========================================
class Estudiante:
    def __init__(self, nombre, id_estudiante, notas, activo=True):
        self.nombre = nombre
        self.id_estudiante = id_estudiante
        self.notas = notas  # Lista de 5 notas
        self.activo = activo

    def obtener_promedio(self):
        return sum(self.notas) / len(self.notas) if self.notas else 0

    def obtener_estado(self):
        return "Aprobado" if self.obtener_promedio() >= 3.0 else "Reprobado"

    def info(self):
        prom = self.obtener_promedio()
        estado = self.obtener_estado()
        return (f"ID: {self.id_estudiante} | Nombre: {self.nombre} | "
                f"Promedio: {prom:.2f} | Estado: {estado}")

# ==========================================
# 2. GESTIÓN DE CRUD Y LÓGICA DE GRUPO
# ==========================================
class GestionEscolar:
    def __init__(self):
        self.estudiantes = []

    def agregar(self, estudiante):
        self.estudiantes.append(estudiante)
        print("\n[OK] Estudiante registrado con éxito.")

    def listar(self):
        if not self.estudiantes:
            print("\n[!] No hay estudiantes en el sistema.")
        else:
            print("\n--- LISTADO DE ESTUDIANTES ---")
            for e in self.estudiantes:
                print(e.info())

    def buscar_por_id(self, id_buscado):
        for e in self.estudiantes:
            if e.id_estudiante == id_buscado:
                return e
        return None

    def buscar_por_nombre(self, nombre_buscado):
        for e in self.estudiantes:
            if e.nombre.lower() == nombre_buscado.lower():
                return e
        return None

    def actualizar_notas(self, id_buscado, nuevas_notas):
        estudiante = self.buscar_por_id(id_buscado)
        if estudiante:
            estudiante.notas = nuevas_notas
            return True
        return False

    def eliminar_estudiante(self, criterio, valor):
        estudiante = None
        if criterio == "id":
            estudiante = self.buscar_por_id(valor)
        elif criterio == "nombre":
            estudiante = self.buscar_por_nombre(valor)

        if estudiante:
            self.estudiantes.remove(estudiante)
            return True
        return False

    def mostrar_reporte_estadistico(self):
        if not self.estudiantes:
            print("\n[!] No hay datos para generar estadísticas.")
            return

        print("\n" + "-"*40)
        print(" REPORTE INDIVIDUAL (NOMBRE Y PROMEDIO) ".center(40))
        print("-"*40)

        promedios_lista = []
        for e in self.estudiantes:
            p = e.obtener_promedio()
            promedios_lista.append(p)
            print(f"Estudiante: {e.nombre.ljust(15)} | Promedio: {p:.2f}")

        prom_grupal = sum(promedios_lista) / len(promedios_lista)
        mejor_nota = max(promedios_lista)
        aprobados = sum(1 for p in promedios_lista if p >= 3.0)
        reprobados = len(promedios_lista) - aprobados

        print("\n" + "-"*40)
        print(" RESUMEN DEL GRUPO ".center(40))
        print("-"*40)
        print(f"Promedio General del Grupo: {prom_grupal:.2f}")
        print(f"Mejor Promedio Alcanzado:   {mejor_nota:.2f}")
        print(f"Total Aprobados:           {aprobados}")
        print(f"Total Reprobados:          {reprobados}")

# ==========================================
# 3. MENÚ POR CONSOLA
# ==========================================
def ejecutar_sistema():
    gestion = GestionEscolar()

    while True:
        print("\n" + "=".center(45, "="))
        print(" SISTEMA DE GESTIÓN ESCOLAR (5 NOTAS) ".center(45, "="))
        print("=".center(45, "="))
        print("1. Agregar Estudiante")
        print("2. Listar Estudiantes")
        print("3. Buscar Estudiante (ID o Nombre)")
        print("4. Actualizar Notas (por ID)")
        print("5. Eliminar Estudiante (ID o Nombre)")
        print("6. Ver Estadísticas del Grupo")
        print("7. Salir")

        opcion = input("\nSeleccione una opción: ")

        if opcion == "1":
            nom = input("Nombre: ")
            idx = input("Identificación: ")
            notas = []
            print("Ingrese las 5 notas (0.0 - 5.0):")
            while len(notas) < 5:
                try:
                    n = float(input(f"  Nota {len(notas)+1}: "))
                    if 0 <= n <= 5: notas.append(n)
                    else: print("  [!] Rango 0-5.")
                except ValueError: print("  [!] Ingrese números.")
            gestion.agregar(Estudiante(nom, idx, notas))

        elif opcion == "2":
            gestion.listar()

        elif opcion == "3":
            print("\n¿Cómo desea buscar?")
            print("1. Por ID")
            print("2. Por Nombre")
            sub_opcion = input("Elija (1/2): ")

            res = None
            if sub_opcion == '1':
                valor = input("Ingrese el ID: ")
                res = gestion.buscar_por_id(valor)
            elif sub_opcion == '2':
                valor = input("Ingrese el Nombre: ")
                res = gestion.buscar_por_nombre(valor)
            else:
                print("[!] Opción inválida.")
                continue

            print(f"\nResultado: {res.info()}" if res else "\n[!] Estudiante no encontrado.")

        elif opcion == "4":
            idx = input("Ingrese ID para actualizar: ")
            if gestion.buscar_por_id(idx):
                nuevas = []
                print("Ingrese las 5 nuevas notas:")
                while len(nuevas) < 5:
                    try:
                        n = float(input(f"  Nota {len(nuevas)+1}: "))
                        if 0 <= n <= 5: nuevas.append(n)
                        else: print("  [!] Rango 0-5.")
                    except ValueError: print("  [!] Ingrese números.")
                gestion.actualizar_notas(idx, nuevas)
                print("\n[OK] Notas actualizadas.")
            else:
                print("\n[!] Estudiante no encontrado.")

        elif opcion == "5":
            print("\n¿Cómo desea eliminar?")
            print("1. Por ID")
            print("2. Por Nombre")
            sub_opcion = input("Elija (1/2): ")

            exito = False
            if sub_opcion == '1':
                valor = input("Ingrese el ID: ")
                exito = gestion.eliminar_estudiante("id", valor)
            elif sub_opcion == '2':
                valor = input("Ingrese el Nombre: ")
                exito = gestion.eliminar_estudiante("nombre", valor)
            else:
                print("[!] Opción inválida.")
                continue

            if exito:
                print("\n[OK] Estudiante eliminado.")
            else:
                print("\n No se encontró el estudiante.")

        elif opcion == "6":
            gestion.mostrar_reporte_estadistico()

        elif opcion == "7":
            print("Cerrando el sistema. ¡Hasta pronto!")
            break
        else:
            print("[!] Opción no válida.")

if __name__== "__main__":
  ejecutar_sistema()